### ISSUE TITLE
Some questions about celluloid life cycle

### ISSUE THREAD

**Issue by dilumnavanjana** [dilumnavanjana/celluloid#11]
@digitalextremist I went through the life cycle of Actor & have some questions to ask from you,

1 - Before an Actor is created, a new mailbox is created AND after creating an Actor, another mailbox is created again. Can you explain this process please?

2 - For an every Actor initialize & every method call, a new task is created. Am I correct?

**Comment by digitalextremist** [comment]
I will be back in the office in a couple hours and I will respond more then!

**Comment by digitalextremist** [comment]
@dilumnavanjana is this what you wanted to have a hangout regarding? If not, can you open an issue with what you do want to discuss? I like to do a little preparation if possible before giving explinations.
