### ISSUE TITLE
Manager.group is null

### ISSUE THREAD

**Issue by dilumnavanjana** [dilumnavanjana/celluloid#41]
Here is my latest code https://github.com/dilumnavanjana/celluloid/commit/1418e78076d12658d57c82c103277a44b8d6e13d

& with that Latest code I'm testing this simple Application [Test Sample](https://gist.github.com/dilumnavanjana/34e629a247490955a504)

I'm going to access `Manager @group` from Unlocker `check_actors` by this.

```Ruby
def check_actors
  @manager.group.each do |actor|
      puts "running Unlocker check_actors"
   end
end
```

But `@manager.group`  is always `null`

I went through the Manager class & noticed that below method doesn't call at any time from my `Test Sample`

```Ruby
def manage!(group)
   @group = group
   every(1.26) { garbage_collector }
end
```
Seems like that's because `group` in `Manager` is always `null`
@digitalextremist do you have any suggestions for this?

**Comment by digitalextremist** [comment]
This is why it's not working:

https://github.com/dilumnavanjana/celluloid/blob/GSoC/2015/lib/celluloid/actor_system.rb#L60

You need to uncomment that in your fork(s)

**Comment by digitalextremist** [comment]
And thank you for writing this ticket in this way, it saves a lot of time, and this is how we work.

**Comment by digitalextremist** [comment]
By the way, that can be `@tree[:group_manager].manage!(@group)`

**Comment by dilumnavanjana** [comment]
This works, Thanks @digitalextremist
